### PR TITLE
Adding an argument for config file path

### PR DESCRIPTION
**Pull request by GreenGremlin**
This change allows passing of the SAML attribute config file as an argument.

### CODE REVIEW

**Comment by GreenGremlin** [comment]
It would be nice to have this change published to npm. The major benefit here is that it is possible to install it from npm, create a local config, and run it without checking out and modifying this repo.

**Comment by GreenGremlin** [comment]
I've also moved the server logic into the `runServer` function and the args logic into the `processArgs` function. This allows `runServer` to be imported by an external script and called directly.

``` javascript
const runServer = require('saml-idp').runServer;

runServer({
  port: 8001,
  key: ...,
  cert: ...,
  issuer: ...,
  etc...
})
```

**Comment by mcguinness** [comment]
Awesome, thx for the PR!  I never had a use case before for NPM as I just used CLI so I kept the package private.  What is your use case?  Might help with naming the package.

**Comment by GreenGremlin** [comment]
We implement SSO SPs for numerous clients and I'm hoping to install saml-idp as an npm global package for mocking clients' IDPs for testing our SP implementations on our dev stacks. Each client has a slightly different attribute configuration, so this PR would allow us to use a single install of saml-idp to test all clients, given individual config files.
I assumed [saml-idp on npm](https://www.npmjs.com/package/saml-idp) was you, but it looks like it's actually [a fork](https://github.com/arijitdasgupta/saml-idp).

**Comment by mcguinness** [comment]
thanks, that helps.  Will investigate the fork and see if I can take it over.

**Comment by mcguinness** [comment]
I took ownership of the existing npm package and published an update https://www.npmjs.com/package/saml-idp

**Comment by GreenGremlin** [comment]
Great! Thanks!

**Pull request merged**
